### ISSUE TITLE
ISDNET code

### ISSUE THREAD

**Issue by Gchang9** [cedricgsh/ISDNet#12]
你好，请问ISDNET的模型还没上传吗？

**Comment by WangZhi-wz** [comment]
> 请问你找到代码了么

**Comment by cedricgsh** [comment]
@Gchang9 
<img width="688" alt="86f3f97f379878dbbf6fcb201dc49e9" src="https://user-images.githubusercontent.com/33807572/222731201-f98dbf01-0403-46aa-b22d-aac525c4552f.png">

**Comment by lizhaoliaooo** [comment]
下载的pretained model好像只有pth文件呀
请问网络结构model在哪

**Comment by songcv** [comment]
按步骤配置的环境怎么总是报错

**Comment by cedricgsh** [comment]
可以参照对应版本的mmsegmentation的tutorial，里边会有对mmcv-full的安装方式 @st9song

**Comment by songcv** [comment]
谢谢回复，安装好了的，最后执行python setup.py develop 会卡住torch2.0
![1685019895822](https://github.com/cedricgsh/ISDNet/assets/107671261/0a4a2659-5bba-4c1d-b06b-39fdfe4be968)
@cedricgsh

**Comment by cedricgsh** [comment]
你为啥安装的是torch2.0? 文档里不是1.6吗

**Comment by songcv** [comment]
> 你为啥安装的是torch2.0? 文档里不是1.6吗

我装的1.6最后执行python setup.py  会自动下载 2.0

**Comment by cedricgsh** [comment]
这个是不是mmseg的问题，可以去问问，对应版本为啥会有这样的问题

**Comment by songcv** [comment]
> 

可以看看你配置过程吗，会不会setup.py的问题

**Comment by songcv** [comment]
> 这个是不是mmseg的问题，可以去问问，对应版本为啥会有这样的问题
![39e87e4f434859d117741c92c3f5b96](https://github.com/cedricgsh/ISDNet/assets/107671261/3dc139a7-4940-4875-b95b-60d51e8b2aa3)
