### ISSUE TITLE
如何使用deepglobe的预训练权重并基于ISDNet进行推理？

### ISSUE THREAD

**Issue by cbachen1997** [cedricgsh/ISDNet#13]
作者您好，
非常感谢您的工作，并将代码进行了开源。
我近期希望基于Deepglobe预训练的模型展开一些研究工作，在使用您的代码时遇到了一些问题。

1. 在使用提供的isdnet_r18-d8_1224x1224_80k_DeepGlobe.py和deepglobe.pth时，通过init_segmentor会出现警告The model and loaded state dict do not match exactly。
既有
unexpected key in source state_dict: 
decode_head.image_pool.1.bn.weight, decode_head.image_pool.1.bn.bias, decode_head.image_pool.1.bn.running_mean, decode_head.image_pool.1.bn.running_var, decode_head.image_pool.1.bn.num_batches_tracked, decode_head.aspp_modules.0.bn.weight, decode_head.aspp_modules.0.bn.bias, decode_head.aspp_modules.0.bn.running_mean, decode_head.aspp_modules.0.bn.running_var,……………………
又有
missing keys in source state_dict:
 decode_head.image_pool.1.conv.bias, decode_head.aspp_modules.0.conv.bias, decode_head.aspp_modules.1.conv.bias, decode_head.aspp_modules.2.conv.bias, decode_head.aspp_modules.3.conv.bias, decode_head.bottleneck.conv.bias,…………
我不知道这是否是由于模型训练、推理阶段的模型结构差异导致的？

2. 在尝试使用demo中的方法，利用deepglobe预训练的ISDNet进行图像分割时，提示EncoderDecoderRefine类缺少out_channel属性。如果直接调用model.encode_decode函数，分类预测结果则非常不理想，不知道是否是问题1导致的。

目前始终无法debug完成正确推理，希望你能解答我的困惑。如果可以的话，能否提供一个利用deepglobe预训练的ISDNet的demo？

**Comment by cbachen1997** [comment]
我尝试使用提供的预训练权重deepglobe.pth，构建出符合该权重的模型，但是提示缺少STDCLpLsRefineHeadArchAff2定义，该类在项目中无法找到。

**Comment by cedricgsh** [comment]
请问您是按照README里的安装流程吗，我从头安装了一遍，可以正常运行
@cbachen1997

**Comment by cbachen1997** [comment]
@cedricgsh 您好，我按照README进行了安装，mmcv相关库均能对应，确实能够运行。
但是问题似乎出在使用的下载的pretrained_model权重deepglobe.pth和configs/isdnet/isdnet_r18-d8_1224x1224_80k_DeepGlobe.py进行推理时，权重与config无法正确匹配，因此按照inference_demo.ipynb推理时效果很差。请问您是使用对应的权重和config文件吗？

**Comment by cedricgsh** [comment]
你的结果是多少，unknown这个类别不用计算在总的mIoU内，但程序输出结果最后是包含了unknown这个的结果，需要自己重新计算除了unknown这个类别之外其他类别的mIoU，README中有除了unknown这个类别之外的其他类别结果，如果都对应的话说明推理没有问题。
@cbachen1997

**Comment by cbachen1997** [comment]
@cedricgsh 您好，我现在并没有需要计算mIOU，只是希望使用deepglobe预训练的isdnet对Deepglobe的图像进行语义分割，目前按照的是demo/inference_demo.ipynb进行推理，使用deepglobe的10452.jpg作为demo图像，得到的结果会得到全为2的预测结果。所以我之前猜想是权重不匹配的问题，如果这不影响，不知是否数据输入前需要进行处理？

**Comment by cedricgsh** [comment]
建议使用整个数据集验证推理结果是否正确，如果整个数据集的mIoU没问题，那么对于特定图像的输出也是没有问题的。

**Comment by cbachen1997** [comment]
您好，按照readme说明，设置好数据集后，我利用tools/test.py对整个数据集进行了测试，使用指标为mIoU。
mIoU效果很差，检查show_dir发现所有图片预测均为黄色，每个像素预测都是相同的结果(0,255,255)。
反复确认多次，完全按照要求进行了测试，仍不知为何出现这种结果。
能否劳烦您检查一下，是否是github项目发布页提供的权重无法与isdnet_r18-d8_1224×1224_80k_DeepGlobe.py对应的问题？或者能否提供一个使用该权重和config进行分割的demo？

**Comment by cedricgsh** [comment]
你的测试命令和最终结果mIoU是多少
我的测试命令是这样的：
python tools/test.py configs/isdnet/isdnet_r18-d8_1224x1224_80k_DeepGlobe.py ./best_models/deepglobe.pth --eval mIoU

**Comment by cedricgsh** [comment]
<img width="192" alt="1679319532029" src="https://user-images.githubusercontent.com/33807572/226356932-f90bd692-2e88-4672-9822-bbbfa462be99.png">
我又重新安装并且运行测试，这个是测试结果。可以看一下你pip list之后的配置库吗

**Comment by cbachen1997** [comment]
非常感谢您耐心细致的回复，我准备重新clone该项目并重新再开一个新环境进行配置测试。
可能是某些难以察觉到的原因导致目前的问题，无论后续我是否能完成测试，我都会再来回复，并附上我的详细情况
再次感谢

**Comment by cbachen1997** [comment]
您好，我已能够正常调试。现在看来是与我此前的mmcv相关库由于路径原因存在冲突导致的问题，这一问题在之前的配置环境过程中没有得到解决。按照您的说明再次配置环境后，问题得到解决。非常感谢您的帮助与回答。

**Comment by cbachen1997** [comment]
您好，我已能够正常调试。现在看来是与我此前的mmcv相关库由于路径原因存在冲突导致的问题，这一问题在之前的配置环境过程中没有得到解决。按照您的说明再次配置环境后，问题得到解决。非常感谢您的帮助与回答。
