### ISSUE TITLE
关于训练和测试的几点疑问

### ISSUE THREAD

**Issue by wwcc1107** [cedricgsh/ISDNet#18]
您好，最近在研究您的工作，发现在复现过程中存在以下几点问题：
1. 论文中提到初始学习率为0.001，但是代码中确实却是保持mmsegmentation的默认配置，即0.01，请问具体训练的时候，学习率是怎样设置的呢？
2. 关于inria aerial数据集，给出的训练配置中，先resize到了5000*0.8，再进行的训练，但是deepglobe数据集确实直接使用原图大小2448进行的训练，这一点论文中并没给出，希望可以得到您的解答？
4. 关于对比实验部分，如deeplabv3+在test集上的预测结果，请问deepglobe的global训练和local训练，图像的数据集具体是多大呢，以及论文中给出的关于inria aerial数据集的对比实验，请问是local训练的结果还是global训练的结果呢，inrai aerial数据集的大小在其他对比模型中的大小又是多少呢？
5. 使用您给出的deepglobe数据集的配置文件进行训练，unknown那一类的iou结果始终为0，请问这个是什么原因呢？因为使用您提供的预训练权重在test集上进行测试，unknown这一类的iou 是有数值的，但是根据您提供的代码进行训练，unknown这一类的iou就没有值。
您的工作非常出色，希望您在百忙之中能回答我的这些疑惑，这将对我的研究工作具有很大的帮助

**Comment by cedricgsh** [comment]
1.以代码为准。
2.使用多大的resize scale取决于你gpu的显存，一般会设置到将显存占满
3.对比实验结果参考其他论文，例如GLNet，PPN等。另外你说的图像数据集多大的问题，是指数据集图像数量还是图像大小，图像大小在论文补充材料中有。
4. test集unknow类别少，因此数值为0，但是测试集中是有一定的unknown像素的。以往论文并不将这一类别算入miou。

**Comment by wwcc1107** [comment]
> 1.以代码为准。 2.使用多大的resize scale取决于你gpu的显存，一般会设置到将显存占满 3.对比实验结果参考其他论文，例如GLNet，PPN等。另外你说的图像数据集多大的问题，是指数据集图像数量还是图像大小，图像大小在论文补充材料中有。 4. test集unknow类别少，因此数值为0，但是测试集中是有一定的unknown像素的。以往论文并不将这一类别算入miou。

好的 谢谢您 我会再做进一步的实验

**Comment by ziyuz-vision** [comment]
@wwcc1107 您好，请问您训练成功了吗，有些问题关于训练想请教下您，您看方便吗
