### ISSUE TITLE
如何使用新的数据集训练

### ISSUE THREAD

**Issue by weichenrs** [cedricgsh/ISDNet#7]
你好！我想用ISDNet在新的数据集上进行训练，该数据有4通道，24个标签类别。我尝试在你的代码上进行修改后训练，但是无法达到基线方法的精度。请问应该如何修改代码？能否麻烦提供一下在新数据集上训练的教程？

**Comment by cedricgsh** [comment]
感谢你关注我们的方法：
1）我们的方法基于mmsegmentaion (version 0.16.0)，关于如何增加新的数据集，你可以参照对应版本的文档进行修改。
2）关于训练，如果图像分辨率和DeepGlobe数据集类似，可以尝试使用DeepGlobe的训练方式。
