### ISSUE TITLE
新数据集训练遇到的问题

### ISSUE THREAD

**Issue by chastloveRYU** [cedricgsh/ISDNet#8]
你好，我使用自己的数据集训练，结果要比切成patch后训练差不少，是不是因为不切片数据量太少的原因，训练集大概401幅1000 x 1000像元。

**Comment by cedricgsh** [comment]
你的四个通道数据，每个通道大概代表什么意思呢

**Comment by chastloveRYU** [comment]
@cedricgsh 你好，是多个波段的遥感图像或者多个极化方式的雷达遥感图像。请教下，数据增强用的随机裁剪，测试的时候是全分辨率，测试的时候需要切片预测再拼接起来吗？

**Comment by cedricgsh** [comment]
不好意思这么晚回复你。对于你的两个问题：
1）对于你提到的多波段遥感图像或者雷达图像，我不是很了解。我们的方法主要以RGB图像为输入，你可以尝试将浅分支的拉普拉斯金字塔去掉，这个操作可能会对你的输入图像产生消极影响。
2）数据增强用的random crop我只在训练中使用，测试时没有使用任何数据增强。关于你说的，测试时是否要拼接，这取决于你如何定义。
