### ISSUE TITLE
Training error on DeepGlobe: nn.upsample_bilinear2d expected output_size equals to 2, but got size 3

### ISSUE THREAD

**Issue by cnstt** [cedricgsh/ISDNet#9]
During training of ISDNet on DeepGlobe with the following script:

`./tools/dist_train.sh configs/isdnet/isdnet_r18-d8_1224x1224_80k_DeepGlobe.py 1`

where `/tools/dist_train.sh` has been just slightly modified to our setup:
```
#!/usr/bin/env bash

CONFIG=$1
GPUS=$2

PYTHONPATH="$(dirname $0)/..":$PYTHONPATH \
python3 -m torch.distributed.launch --nproc_per_node=$GPUS \
    $(dirname "$0")/train.py $CONFIG --launcher pytorch ${@:3}
```

We get the following error:

```
[...]
  File "/path/ISDNet/mmseg/models/decode_heads/refine_decode_head.py", line 217, in losses
    seg_logit = resize(
  File "/path/ISDNet/mmseg/ops/wrappers.py", line 26, in resize
    return F.interpolate(input, size, scale_factor, mode, align_corners)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/functional.py", line 3163, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, sfl[0], sfl[1])
RuntimeError: It is expected output_size equals to 2, but got size 3
```
We have neither modified train.py nor the ISDnet model itself (taken as is from this git directory).
The DeepGlobe dataset has been split like requested, so we don't think this might be the issue. Or is there some preprocessing needed that we missed?
Do you have any idea why this error occurred, and where it might have come from?
Thanks again in advance for your help!

**Comment by cedricgsh** [comment]
Sorry for late. Have you check the number of the channel of labels？Official labels are RGB images that cannot directly apply on training.

**Comment by cnstt** [comment]
> Sorry for late. Have you check the number of the channel of labels？Official labels are RGB images that cannot directly apply on training.

Thanks for your response. We managed to solve our issue by using an adapted version of this script: https://www.kaggle.com/code/bulentsiyah/preprocessing-rgb-img-masks-to-segmentation-masks/notebook

Maybe it would be usefull to add a small warning in the readme, that the transformation to segmentation masks is needed. This could be useful for new people discovering this repository :)

**Comment by ziyuz-vision** [comment]
@cnstt Did you run successfully in training. If so, I wish you can help with some issues during my training. Thx!
